### ISSUE TITLE
Missing "dev mode deploy" setting?

### ISSUE THREAD

**Issue by FreekVR** [workingconcept/trigger-craft-plugin#5]
Hi!

First of all, thanks so much for this plugin, this is exactly what we need for a project I'm working on! 

I was testing the automatic deploy on content change feature, and thought it wasn't working, until I found a reference in code 
` if ($this->getSettings()->active && (! $isDevMode || $this->getSettings()->devModeDeploy))`

So it seems it's not running on dev mode, which seems sensible, but it IS referencing a plugin setting I can't find anywhere, perhaps an unimplemented feature?

Regardless, perhaps it would help to add the setting, or otherwise a small remark in the readme, just in case someone else runs into the same problem.

**Comment by mattstein** [comment]
Hi @FreekVR, glad this plugin’s been useful!

The [`devModeDeploy` setting exists](https://github.com/workingconcept/trigger-craft-plugin/blob/develop/src/models/Settings.php#L39) and works, it’s just not exposed in the control panel UI and `false` by default.

The assumption is that anyone testing this locally would only be a developer doing so temporarily, so the setting is there just for convenience—if you create `config/trigger.php` you can change it there:

```php
<?php

return [
    'devModeDeploy' => true
];
```

**Comment by FreekVR** [comment]
Ah thanks, that makes a bit more sense then :)
