### ISSUE TITLE
incompatible with your PHP version... 7.4.5

### ISSUE THREAD

**Issue by magicspon** [workingconcept/trigger-craft-plugin#7]
Hello,

I'm getting the following error when I try to install this via composer

```
[InvalidArgumentException]                                                                                       
  Package workingconcept/craft-trigger at version  has a PHP requirement incompatible with your PHP version (7.0) 
```

php -v === 7.4.5

Any thoughts?

Thanks
Dave

**Comment by mattstein** [comment]
That exception says you’re running PHP 7.0 even though you’re saying it’s 7.4.5. Any chance you’re running `composer install` on your local system while your site’s running in a Nitro machine or Docker container?

**Comment by magicspon** [comment]
Heyo..

I'm using Homestead, so I'm running `vagrant ssh` to get onto the box, and then i run composer from there... 
![image](https://user-images.githubusercontent.com/3268717/99732834-1b948780-2ab8-11eb-842e-1a0855f3fcdd.png)

No idea why it says 7.0, php -v returns 7.4.5, and the php info section in craft also says 7.4.5

How bizarre!

**Comment by mattstein** [comment]
I’m puzzled.

I’m only running PHP 7.4.12 with Composer 2, but I can run `composer require workingconcept/craft-trigger` just fine.

Does it make any difference if you change this plugin’s composer.json version requirement from `"php": "^7.1.0",` to `"php": ">=7.1.0",`?

You could also try running composer with the `--ignore-platform-reqs` argument to get around the install issue, but you’ll want to make sure that doesn’t result in some other weird bugs if PHP 7.0 really is part of the equation here.

**Comment by magicspon** [comment]
Waaa, sorry I completely forgot to get back to you.
I've just successfully installed it on a new project... I'll close this issue now
