### ISSUE TITLE
Add support for PHP 8

### ISSUE THREAD

**Issue by sandren** [workingconcept/trigger-craft-plugin#8]
Currently version PHP 7.1 is required.

@mattstein I wouldn't mind opening a PR to update `composer.json` if you trust that there are no changes required within the code itself.

**Comment by mattstein** [comment]
Thanks @sandren! I just tagged [0.4.0](https://github.com/workingconcept/trigger-craft-plugin/releases/tag/0.4.0), which removes this plugin’s redundant PHP requirement. I’ve been using it with PHP for a while now and there’s not a whole lot going on, so it should be safe.
